name: sistema_revenda
description: Envio de email usando Dart e Mailer
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mailer: ^6.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0